---
title: "integration_benefit_ABM"
author: "Stine Fabech Hansson"
date: "2/1/2021"
output:   
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import packages + wd
```{r}
library(pacman)
p_load(tidyverse)
p_load(sf, lwgeom)
p_load(rgdal)
p_load(doBy) #which.minn
p_load(plyr) #empty()
p_load(system.time) #Get runtime

setwd("C:/Users/stine/OneDrive/Cognitive Science/5th_Semester/bachelor/ABM_Aarhus")
```

################################## Agents Choose Preferred Home ###############################

Import preferred postcodes overall + functions: 
```{r}
#Importing the overall prefered postcodes by each type 
overall_k_h <- read_csv("overall_k_h.csv")
overall_k_l <- read_csv("overall_k_l.csv")
overall_n_h <- read_csv("overall_n_h.csv")
overall_n_l <- read_csv("overall_n_l.csv")
overall_k_l_i <- read_csv("overall_k_l_i.csv")
overall_n_l_i <- read_csv("overall_n_l_i.csv")

#Find the best postcode for type:

#Import cheap postcodes: 
cheap_postcodes <- read_csv("cheapest_postcodes.csv")
cheap_postcodes_restrict <- cheap_postcodes[-c(2),]

###################################kids_low_economy_int ####################################
pref_kids_low_int <- function(environment){
  df <- filter(environment, environment$Postalcodes %in% cheap_postcodes_restrict$Postcodes)

  if (length(df$Postalcodes)>1){
    df <- filter(df, df$Perc_non_western_im_desc > 5)
  } 
  if (length(df$Postalcodes)>1){
    small <- which.minn(df$Green_area_distance, n = 5)
    df <- filter(df, df$Green_area_distance %in% df$Green_area_distance[small])
  } 
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$School_rating, n = 3)
    df <- filter(df, df$School_rating %in% df$School_rating[small])
  } 
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$Public_transport_distance, n = 2)
    df <- filter(df, df$Public_transport_distance %in% df$Public_transport_distance[small])
  } 
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$Min_Mall_distance, n = 1)
    df <- filter(df, df$Min_Mall_distance %in% df$Min_Mall_distance[small])
  }
  return(df)
}

#################################### no_kids_low_economy_int ##################################

pref_no_kids_low_int <- function(environment){
  df <- filter(environment, environment$Postalcodes %in% cheap_postcodes_restrict$Postcodes)
  
  if (length(df$Postalcodes)>1){
    df <- filter(df, df$Perc_non_western_im_desc > 5)
    
  } 
  if (length(df$Postalcodes)>1){
    small <- which.minn(df$Green_area_distance, n = 5)
    df <- filter(df, df$Green_area_distance %in% df$Green_area_distance[small])
  }
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$Public_transport_distance, n = 2)
    df <- filter(df, df$Public_transport_distance %in% df$Public_transport_distance[small])
  } 
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$Min_Mall_distance, n = 1)
    df <- filter(df, df$Min_Mall_distance %in% df$Min_Mall_distance[small])
  }
  return(df)
}

########################################## kids_low_economy #############################
pref_kids_low <- function(environment){
  df <- filter(environment, environment$Postalcodes %in% cheap_postcodes$Postcodes
  |environment$Postalcodes %in% c(8220))

  if (length(df$Postalcodes)>1){
    df <- filter(df, df$Perc_non_western_im_desc > 5)
  } 
  if (length(df$Postalcodes)>1){
    small <- which.minn(df$Green_area_distance, n = 5)
    df <- filter(df, df$Green_area_distance %in% df$Green_area_distance[small])
  } 
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$School_rating, n = 3)
    df <- filter(df, df$School_rating %in% df$School_rating[small])
  } 
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$Public_transport_distance, n = 2)
    df <- filter(df, df$Public_transport_distance %in% df$Public_transport_distance[small])
  } 
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$Min_Mall_distance, n = 1)
    df <- filter(df, df$Min_Mall_distance %in% df$Min_Mall_distance[small])
  }
  return(df)
}



############################################ kids_high_economy ##############################
pref_kids_high <- function(environment){
  df <- filter(environment, environment$Owner_oc_housing_m2 >=                               mean(environment$Owner_oc_housing_m2)-(sd(environment$Owner_oc_housing_m2)/2))

  if (length(df$Postalcodes)>1){
    df <- filter(df, df$Perc_non_western_im_desc > 5)
  } 
  if (length(df$Postalcodes)>1){
    small <- which.minn(df$Green_area_distance, n = 5)
    df <- filter(df, df$Green_area_distance %in% df$Green_area_distance[small])
  } 
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$School_rating, n = 3)
    df <- filter(df, df$School_rating %in% df$School_rating[small])
  } 
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$Public_transport_distance, n = 2)
    df <- filter(df, df$Public_transport_distance %in% df$Public_transport_distance[small])
  } 
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$Min_Mall_distance, n = 1)
    df <- filter(df, df$Min_Mall_distance %in% df$Min_Mall_distance[small])
  }
  return(df)
}



#################################### no_kids_low_economy ######################################
pref_no_kids_low <- function(environment){
  df <- filter(environment, environment$Postalcodes %in% cheap_postcodes$Postcodes
  |environment$Postalcodes %in% c(8220))
  
  if (length(df$Postalcodes)>1){
    df <- filter(df, df$Perc_non_western_im_desc > 5)
    
  } 
  if (length(df$Postalcodes)>1){
    small <- which.minn(df$Green_area_distance, n = 5)
    df <- filter(df, df$Green_area_distance %in% df$Green_area_distance[small])
  }
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$Public_transport_distance, n = 2)
    df <- filter(df, df$Public_transport_distance %in% df$Public_transport_distance[small])
  } 
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$Min_Mall_distance, n = 1)
    df <- filter(df, df$Min_Mall_distance %in% df$Min_Mall_distance[small])
  }
  return(df)
}



##################################### no_kids_high_economy ###################################
pref_no_kids_high <- function(environment){
  df <- filter(environment, environment$Owner_oc_housing_m2 >=                               mean(environment$Owner_oc_housing_m2)-(sd(environment$Owner_oc_housing_m2)/2))

  if (length(df$Postalcodes)>1){
    df <- filter(df, df$Perc_non_western_im_desc > 5)
  } 
  if (length(df$Postalcodes)>1){
    small <- which.minn(df$Green_area_distance, n = 5)
    df <- filter(df, df$Green_area_distance %in% df$Green_area_distance[small])
  }
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$Public_transport_distance, n = 2)
    df <- filter(df, df$Public_transport_distance %in% df$Public_transport_distance[small])
  } 
  if (length(df$Postalcodes)>1) {
    small <- which.minn(df$Min_Mall_distance, n = 1)
    df <- filter(df, df$Min_Mall_distance %in% df$Min_Mall_distance[small])
  }
  return(df)
}


```


Agents: 
```{r}
# Assuming having kids and once economic level are independent these are the following probabilities of belonging to each group
# kids_low_economy 0.5*0.35=17.5 % rond up 
# kids_high_economy 0.5*0.35=17.5 % 
# no_kids_low_economy 0.5*0.65 =32.5% round up 
# no_kids_high_economy 0.5*0.65 =32.5%

envi <- read_csv2("environment_aarhus.csv")
envi <- envi[,-c(1, 4:5)] # Dropping unnecessary columns
envi_restrict <- envi[-c(3:4),]

n= 100 # number of households set to 16656

kids_low_economy <- rep("kids_low_economy", round(n* 0.165))
kids_high_economy <- rep("kids_high_economy", round(n* 0.175))
no_kids_low_economy <- rep("no_kids_low_economy", round(n* 0.310))
no_kids_high_economy <- rep("no_kids_high_economy", floor(n* 0.325))
kids_low_economy_int <- rep("kids_low_economy_int", round(n* 0.010))
no_kids_low_economy_int <- rep("no_kids_low_economy_int", round(n* 0.015))


pref <- data.frame(matrix(ncol = 4, nrow = n)) # Empty dataframe to put in the preferences of people
colnames(pref)<- c("agent_type", "equally_good_1", "original_postcode", "move_1")

pref$agent_type <- c(kids_low_economy, kids_high_economy, no_kids_low_economy, no_kids_high_economy, kids_low_economy_int, no_kids_low_economy_int)
pref$equally_good_1 <- 0
#REMEMBER TO SET SEED 
## Place the types randomly in a postcode
set.seed(8376) # 487 # 8376 # 3728
pref$original_postcode <- sample(envi$Postalcodes, length(pref$agent_type), replace = TRUE)

# make sure that agent_types kids_low_economy_int and no_kids_low_economy_int are not originally placed in 8210  nor 8220 
ifelse(pref$agent_type == "kids_high_economy" | pref$agent_type=="no_kids_high_economy"
        |pref$agent_type=="kids_low_economy" | pref$agent_type=="no_kids_low_economy",
         
         pref$original_postcode[pref$agent_type=="kids_high_economy"|pref$agent_type=="no_kids_high_economy"| pref$agent_type=="kids_low_economy" | pref$agent_type=="no_kids_low_economy"] <-
          sample(envi$Postalcodes, length(pref$agent_type[pref$agent_type=="kids_high_economy" | pref$agent_type=="no_kids_high_economy" | pref$agent_type=="kids_low_economy" | pref$agent_type=="no_kids_low_economy"]), replace = TRUE),
          
pref$original_postcode[pref$agent_type=="kids_low_economy_int"|pref$agent_type=="no_kids_low_economy_int"] <- sample(envi_restrict$Postalcodes, length(pref$agent_type[pref$agent_type=="kids_low_economy_int" | pref$agent_type=="no_kids_low_economy_int"]), replace = TRUE))

pref$move_1 <- 0 # Has to have something different from NA in the first column before beginning



```

Loop for finding preferred postcode 
```{r}
#Import environment 
envi <- read_csv2("environment_aarhus.csv")
envi <- envi[,-c(1, 4:5)] # Dropping unnecessary columns
envi_restrict <- envi[-c(3:4),]
#Import neighbouring postcodes 
neigh <- read_csv2("neighbouring_postcodes.csv")

emp <- as.data.frame(matrix(10000, nrow = 1, ncol = 9))
colnames(emp) <- colnames(envi)

emp_high <- emp
emp_high$Almenbolig_sd_rent <- 0

i=4
j=1

#################################### Simulation FUNCTION #####################################

simulation <- function(preferences, overall_kids_low, overall_kids_high, overall_no_low, overall_no_high, environment, environment_restrict, neigh_postcodes, empty, empty_high){

  while (sum(is.na(preferences[,i])) < length(preferences$agent_type)){ # Continue while at least one agent is still moving
    t=i-2
    preferences[[paste0("move_",t)]] <- NA#Add new columns as necessary 
    
    for (i in 4:ncol(preferences)){ # Looping over newly created columns
      
      for (j in 1:length(preferences$agent_type)){ # Looping over all agents 
        
      if (is.na(preferences[j,i-1])){
        next
      } 
############################################ Kids Low ##################################
        if (preferences$agent_type[j] == "kids_low_economy"){ 
          
          # Finding the nearby postcodes for the postcode the agent is currently living in 
          near <- filter(neigh_postcodes, neigh_postcodes$Postalcodes == preferences[j,i-1]) 
          # Finding preferred postcode among surrounding neighborhoods 
          pref_near <- filter(environment, environment$Postalcodes %in% near[2:9]) %>% pref_kids_low()
          
          # compare current, surrounding, and all-time preferred postcode
          # Need to stay if neither the all preferred nor the surrounding is better on multiple counts
  
          #Check that pref_near has data. If not set row three = 0 
          ifelse(empty(pref_near), 
                 prefered <- rbind(filter(environment, environment$Postalcodes %in% 
                                     preferences[j,i-1]), overall_k_l, empty), 
                 prefered <- rbind(filter(environment, environment$Postalcodes %in% 
                                     preferences[j,i-1]), overall_k_l, pref_near))
           
          #Prefered neighbouring postcode Vs. Current postcode 
         if(sum(prefered$Almenbolig_sd_rent[[3]] < prefered$Almenbolig_sd_rent[[1]], 
             prefered$Green_area_distance[[3]] < prefered$Green_area_distance[[1]])>=1){
              
              preferences[j,i] <- prefered$Postalcodes[3]
              
          #If household has moved back and forth between two postcodes then choose one at random
           if(i>=6 && !any(is.na(preferences[j,(i-3):i])) && 
              sum(preferences[j,(i-3):(i-2)] == preferences[j,(i-1):(i)])==2){
              preferences[j,i-1] <- sample(preferences[j,(i-1):i], 1, prob = c(0.5, 0.5))
              preferences[j,i] <- NA
              preferences[j,2] <- 1
            }   
              
            #Overall prefered vs. Current postcode   
          } else if (sum(prefered$Almenbolig_sd_rent[[2]] < prefered$Almenbolig_sd_rent[[1]],
          prefered$Green_area_distance[[2]] < prefered$Green_area_distance[[1]],
          prefered$School_rating[[2]] < prefered$School_rating[[1]], 
          prefered$Public_transport_distance[[2]] < prefered$Public_transport_distance[[1]])>=3 &
          is.na(preferences[j,i])){ # Larger than 3 is too harsh 
            
            preferences[j,i] <- prefered$Postalcodes[2]
          
          #If household has moved back and forth between two postcodes then choose one at random
            if(i>=6 && !any(is.na(preferences[j,(i-3):i])) && 
              sum(preferences[j,(i-3):(i-2)] == preferences[j,(i-1):(i)])==2){
              preferences[j,i-1] <- sample(preferences[j,(i-1):i], 1, prob = c(0.5, 0.5))
              preferences[j,i] <- NA
              preferences[j,2] <- 1
            }
            
          } else {
            preferences[j,i] <- NA

          }

########################################## KIDS HIGH #########################################
        } else if (preferences$agent_type[j] == "kids_high_economy") {
          
          # Finding the nearby postcodes for the postcode the agent is currently living in 
          near <- filter(neigh_postcodes, neigh_postcodes$Postalcodes == preferences[j,i-1]) 
          # Finding preferred postcode among surrounding neighborhoods 
          pref_near <- filter(environment, environment$Postalcodes %in% near[2:9]) %>% pref_kids_high()
          
          # compare current, all-time preferred postcode, and prefered surrounding
          # Need to stay if neither the all preferred nor the surrounding is better on multiple counts
  
          #Check that pref_near has data. If not set row three = 0
          ifelse(empty(pref_near), 
                 prefered <- rbind(filter(environment, environment$Postalcodes %in% 
                                     preferences[j,i-1]), overall_k_h, empty_high), 
                 prefered <- rbind(filter(environment, environment$Postalcodes %in% 
                                     preferences[j,i-1]), overall_k_h, pref_near))
           
          # Prefered Neighbouring postcode vs. current postcode
         if(sum(prefered$Owner_oc_housing_m2 [[3]] > prefered$Owner_oc_housing_m2[[1]], 
             prefered$Green_area_distance[[3]] < prefered$Green_area_distance[[1]])>=1){
              
              preferences[j,i] <- prefered$Postalcodes[3]
              
        #If household has moved back and forth between two postcodes then choose one at random
            if(i>=6 && !any(is.na(preferences[j,(i-3):i])) && 
              sum(preferences[j,(i-3):(i-2)] == preferences[j,(i-1):(i)])==2){
              preferences[j,i-1] <- sample(preferences[j,(i-1):i], 1, prob = c(0.5, 0.5))
              preferences[j,i] <- NA
              preferences[j,2] <- 1
            }
              # Overall prefered postcode vs. current postcode 
          } else if (sum(prefered$Owner_oc_housing_m2[[2]] > prefered$Owner_oc_housing_m2[[1]],
          prefered$Green_area_distance[[2]] < prefered$Green_area_distance[[1]],
          prefered$School_rating[[2]] < prefered$School_rating[[1]], 
          prefered$Public_transport_distance[[2]] < prefered$Public_transport_distance[[1]])>=3 &
          is.na(preferences[j,i])){ # Larger than 3 is too harsh 
            
            preferences[j,i] <- prefered$Postalcodes[2]
          
          #If household has moved back and forth between two postcodes then choose one at random
            if(i>=6 && !any(is.na(preferences[j,(i-3):i])) && 
              sum(preferences[j,(i-3):(i-2)] == preferences[j,(i-1):(i)])==2){
              preferences[j,i-1] <- sample(preferences[j,(i-1):i], 1, prob = c(0.5, 0.5))
              preferences[j,i] <- NA
              preferences[j,2] <- 1
            }
            
          } else {
            preferences[j,i] <- NA

          }
  
######################################### NO KIDS LOW ########################################
        } else if (preferences$agent_type[j] == "no_kids_low_economy") {
          
          # Finding the nearby postcodes for the postcode the agent is currently living in 
          near <- filter(neigh_postcodes, neigh_postcodes$Postalcodes == preferences[j,i-1]) 
          # Finding preferred postcode among surrounding neighborhoods 
          pref_near <- filter(environment, environment$Postalcodes %in% near[2:9]) %>% pref_no_kids_low()
          
          # compare current, surrounding, and all-time preferred postcode
          # Need to stay if neither the all preferred nor the surrounding is better on multiple counts
  
          #Check that pref_near has data. If not set row three = 0
          ifelse(empty(pref_near), 
                 prefered <- rbind(filter(environment, environment$Postalcodes %in% 
                                     preferences[j,i-1]), overall_n_l, empty), 
                 prefered <- rbind(filter(environment, environment$Postalcodes %in% 
                                     preferences[j,i-1]), overall_n_l, pref_near))
           
          # Prefered neighbouring postcode VS. current postcode 
         if(sum(prefered$Almenbolig_sd_rent[[3]] < prefered$Almenbolig_sd_rent[[1]], 
             prefered$Green_area_distance[[3]] < prefered$Green_area_distance[[1]])>=1){
              
              preferences[j,i] <- prefered$Postalcodes[3]
              
          #If household has moved back and forth between two postcodes then choose one at random
            if(i>=6 && !any(is.na(preferences[j,(i-3):i])) && 
              sum(preferences[j,(i-3):(i-2)] == preferences[j,(i-1):(i)])==2){
              preferences[j,i-1] <- sample(preferences[j,(i-1):i], 1, prob = c(0.5, 0.5))
              preferences[j,i] <- NA
              preferences[j,2] <- 1
            }
          #Overall prefered postcode Vs. Current postcode 
          } else if (sum(prefered$Almenbolig_sd_rent[[2]] < prefered$Almenbolig_sd_rent[[1]],
          prefered$Green_area_distance[[2]] < prefered$Green_area_distance[[1]],
          prefered$Public_transport_distance[[2]] < prefered$Public_transport_distance[[1]])>=3 &
          is.na(preferences[j,i])){ # Larger than 3 is too harsh 
            
            preferences[j,i] <- prefered$Postalcodes[2]
          
         #If household has moved back and forth between two postcodes then choose one at random 
            if(i>=6 && !any(is.na(preferences[j,(i-3):i])) && 
              sum(preferences[j,(i-3):(i-2)] == preferences[j,(i-1):(i)])==2){
              preferences[j,i-1] <- sample(preferences[j,(i-1):i], 1, prob = c(0.5, 0.5))
              preferences[j,i] <- NA
              preferences[j,2] <- 1
            }
            
          } else {
            preferences[j,i] <- NA

          }
  
##################################### NO KIDS HIGH ########################################
        } else if (preferences$agent_type[j] == "no_kids_high_economy") {
          
          # Finding the nearby postcodes for the postcode the agent is currently living in 
          near <- filter(neigh_postcodes, neigh_postcodes$Postalcodes == preferences[j,i-1]) 
          # Finding preferred postcode among surrounding neighborhoods 
          pref_near <- filter(environment, environment$Postalcodes %in% near[2:9]) %>% pref_no_kids_high()
          
          # compare current, surrounding, and all-time preferred postcode
          # Need to stay if neither the all preferred nor the surrounding is better on multiple counts
  
          #Check that pref_near has data. If not set row three = 0
          ifelse(empty(pref_near), 
                 prefered <- rbind(filter(environment, environment$Postalcodes %in% 
                                     preferences[j,i-1]), overall_n_h, empty_high), 
                 prefered <- rbind(filter(environment, environment$Postalcodes %in% 
                                     preferences[j,i-1]), overall_n_h, pref_near))
           
          # Prefered neighbouring postcode VS. current postcode 
         if(sum(prefered$Owner_oc_housing_m2[[3]] > prefered$Owner_oc_housing_m2[[1]], 
             prefered$Green_area_distance[[3]] < prefered$Green_area_distance[[1]])>=1){
              
              preferences[j,i] <- prefered$Postalcodes[3]
            
            if(i>=6 && !any(is.na(preferences[j,(i-3):i])) && 
              sum(preferences[j,(i-3):(i-2)] == preferences[j,(i-1):(i)])==2){
              preferences[j,i-1] <- sample(preferences[j,(i-1):i], 1, prob = c(0.5, 0.5))
              preferences[j,i] <- NA
              preferences[j,2] <- 1
            }
              # Overall prefered  VS. Current postcode 
          } else if (sum(prefered$Owner_oc_housing_m2[[2]] > prefered$Owner_oc_housing_m2[[1]],
          prefered$Green_area_distance[[2]] < prefered$Green_area_distance[[1]],
          prefered$Public_transport_distance[[2]] < prefered$Public_transport_distance[[1]])>=3 &
          is.na(preferences[j,i])){ # Larger than 3 is too harsh 
            
            preferences[j,i] <- prefered$Postalcodes[2]
        
        #If household has moved back and forth between two postcodes then choose one at random
            if(i>=6 && !any(is.na(preferences[j,(i-3):i])) && 
              sum(preferences[j,(i-3):(i-2)] == preferences[j,(i-1):(i)])==2){
              preferences[j,i-1] <- sample(preferences[j,(i-1):i], 1, prob = c(0.5, 0.5))
              preferences[j,i] <- NA
              preferences[j,2] <- 1
            }
            
          } else {
            preferences[j,i] <- NA

          }
################################## Kids low economy integration ############################
        } else if (preferences$agent_type[j] == "kids_low_economy_int"){ 
          
          # Finding the nearby postcodes for the postcode the agent is currently living in 
          near <- filter(neigh_postcodes, neigh_postcodes$Postalcodes == preferences[j,i-1]) 
          # Finding preferred postcode among surrounding neighborhoods 
          pref_near <- filter(environment_restrict, environment_restrict$Postalcodes %in% near[2:9]) %>%
            pref_kids_low_int()
          
          # compare current, surrounding, and all-time preferred postcode
          # Need to stay if neither the all preferred nor the surrounding is better on multiple counts
  
          #Check that pref_near has data. If not set row three = 0 ######## PROBLEM###
          ifelse(empty(pref_near), 
                 prefered <- rbind(filter(environment_restrict, environment_restrict$Postalcodes %in% 
                                     preferences[j,i-1]), overall_k_l_i, empty), 
                 prefered <- rbind(filter(environment_restrict, environment_restrict$Postalcodes %in% 
                                     preferences[j,i-1]), overall_k_l_i, pref_near))
           
          #Prefered neighbouring postcode Vs. Current postcode 
         if(sum(prefered$Almenbolig_sd_rent[[3]] < prefered$Almenbolig_sd_rent[[1]], 
             prefered$Green_area_distance[[3]] < prefered$Green_area_distance[[1]])>=1){
              
              preferences[j,i] <- prefered$Postalcodes[3]
            
        #If household has moved back and forth between two postcodes then choose one at random
           if(i>=6 && !any(is.na(preferences[j,(i-3):i])) && 
              sum(preferences[j,(i-3):(i-2)] == preferences[j,(i-1):(i)])==2){
              preferences[j,i-1] <- sample(preferences[j,(i-1):i], 1, prob = c(0.5, 0.5))
              preferences[j,i] <- NA
              preferences[j,2] <- 1
            }   
              
            #Overall prefered vs. Current postcode   
          } else if (sum(prefered$Almenbolig_sd_rent[[2]] < prefered$Almenbolig_sd_rent[[1]],
          prefered$Green_area_distance[[2]] < prefered$Green_area_distance[[1]],
          prefered$School_rating[[2]] < prefered$School_rating[[1]], 
          prefered$Public_transport_distance[[2]] < prefered$Public_transport_distance[[1]])>=3 &
          is.na(preferences[j,i])){ # Larger than 3 is too harsh 
            
            preferences[j,i] <- prefered$Postalcodes[2]
            
        #If household has moved back and forth between two postcodes then choose one at random
            if(i>=6 && !any(is.na(preferences[j,(i-3):i])) && 
              sum(preferences[j,(i-3):(i-2)] == preferences[j,(i-1):(i)])==2){
              preferences[j,i-1] <- sample(preferences[j,(i-1):i], 1, prob = c(0.5, 0.5))
              preferences[j,i] <- NA
              preferences[j,2] <- 1
            }
            
          } else {
            preferences[j,i] <- NA

          }

#################################### NO KIDS LOw Integration ################################# 
        } else if (preferences$agent_type[j] == "no_kids_low_economy_int") {
          
          # Finding the nearby postcodes for the postcode the agent is currently living in 
          near <- filter(neigh_postcodes, neigh_postcodes$Postalcodes == preferences[j,i-1]) 
          # Finding preferred postcode among surrounding neighborhoods 
          pref_near <- filter(environment_restrict, environment_restrict$Postalcodes %in% near[2:9]) %>%
            pref_no_kids_low_int()
          
          # compare current, surrounding, and all-time preferred postcode
          # Need to stay if neither the all preferred nor the surrounding is better on multiple counts
  
          #Check that pref_near has data. If not set row three = 0
          ifelse(empty(pref_near), 
                 prefered <- rbind(filter(environment_restrict, environment_restrict$Postalcodes %in% 
                                     preferences[j,i-1]), overall_n_l_i, empty), 
                 prefered <- rbind(filter(environment_restrict, environment_restrict$Postalcodes %in% 
                                     preferences[j,i-1]), overall_n_l_i, pref_near))
           
          # Prefered neighbouring postcode VS. current postcode 
         if(sum(prefered$Almenbolig_sd_rent[[3]] < prefered$Almenbolig_sd_rent[[1]], 
             prefered$Green_area_distance[[3]] < prefered$Green_area_distance[[1]])>=1){
              
              preferences[j,i] <- prefered$Postalcodes[3]
            
          #If household has moved back and forth between two postcodes then choose one at random
            if(i>=6 && !any(is.na(preferences[j,(i-3):i])) && 
              sum(preferences[j,(i-3):(i-2)] == preferences[j,(i-1):(i)])==2){
              preferences[j,i-1] <- sample(preferences[j,(i-1):i], 1, prob = c(0.5, 0.5))
              preferences[j,i] <- NA
              preferences[j,2] <- 1
            }
          #Overall prefered postcode Vs. Current postcode 
          } else if (sum(prefered$Almenbolig_sd_rent[[2]] < prefered$Almenbolig_sd_rent[[1]],
          prefered$Green_area_distance[[2]] < prefered$Green_area_distance[[1]],
          prefered$Public_transport_distance[[2]] < prefered$Public_transport_distance[[1]])>=3 &
          is.na(preferences[j,i])){ # Larger than 3 is too harsh 
            
            preferences[j,i] <- prefered$Postalcodes[2]
             
          #If household has moved back and forth between two postcodes then choose one at random
            if(i>=6 && !any(is.na(preferences[j,(i-3):i])) && 
              sum(preferences[j,(i-3):(i-2)] == preferences[j,(i-1):(i)])==2){
              preferences[j,i-1] <- sample(preferences[j,(i-1):i], 1, prob = c(0.5, 0.5))
              preferences[j,i] <- NA
              preferences[j,2] <- 1
            }
            
          } else {
            preferences[j,i] <- NA

          }
        }
        
      }
    }
  }

  return(preferences)
}

```


RESTRCTION SIMULATIONS 
```{r}
# RESTRCTION: Integration-Benefit

system.time({int_sim_1 <-simulation(pref, overall_k_l, overall_k_h, overall_n_l, overall_n_h, envi, envi_restrict, neigh, emp, emp_high)})
#write.csv(int_sim_1, "int_sim_1.csv", row.names = FALSE)

system.time({int_sim_2 <-simulation(pref, overall_k_l, overall_k_h, overall_n_l, overall_n_h, envi, envi_restrict, neigh, emp, emp_high)})
#write.csv(int_sim_2, "int_sim_2.csv", row.names = FALSE)
```

